import type { APIRoute } from "astro";
import {
  AUTHOR,
  INSTALL,
  INTRO,
  REPO_URL,
  SITE_URL,
  SKILL_CHOOSER,
  SOFTWARE_APPLICATION,
  TAGLINE,
  markdownResponse,
  skillCatalog,
} from "../utils/site";

// The homepage as Markdown, served by the edge Worker to clients that send
// `Accept: text/markdown` for `/`.
export const GET: APIRoute = () =>
  markdownResponse(
    {
      title: "Clairvoyance",
      description: SOFTWARE_APPLICATION.description,
      canonical: `${SITE_URL}/`,
    },
    [
      "# Clairvoyance",
      "",
      `> ${TAGLINE}`,
      "",
      ...INTRO,
      "",
      "## Install",
      "",
      "Claude Code:",
      "",
      "```",
      INSTALL.claudeStep1,
      INSTALL.claudeStep2,
      "```",
      "",
      "Other agents (via [skills.sh](https://skills.sh/codybrom/clairvoyance)):",
      "",
      "```bash",
      INSTALL.skillsSh,
      "```",
      "",
      `Any LLM: load [llms-full.txt](${SITE_URL}/llms-full.txt), every skill in one file.`,
      "",
      `Instructions for Codex, Cursor, OpenCode, Antigravity and more: ${REPO_URL}#installation`,
      "",
      "## Skills",
      "",
      ...skillCatalog(3),
      ...SKILL_CHOOSER,
      "",
      "## Links",
      "",
      `- [GitHub](${REPO_URL})`,
      `- [All skills](${SITE_URL}/skills)`,
      `- [About](${SITE_URL}/about)`,
      `- [Contact](${SITE_URL}/contact)`,
      `- [Privacy](${SITE_URL}/privacy)`,
      `- [llms.txt](${SITE_URL}/llms.txt)`,
      "",
      `Created by [${AUTHOR.name}](${AUTHOR.url}). Inspired by *A Philosophy of Software Design* by John K. Ousterhout. Licensed under the [MIT License](${REPO_URL}/blob/main/LICENSE).`,
      "",
    ],
  );
